[package]
name = "ghsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
http = "0.2"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
gluesql = { version = "0.9", default-features = false, features = ["sorter"] }
async-trait = "0.1"
rustyline = "9.1"
structopt = "0.3"
